#!/usr/bin/env python3
"""mkblocks.py - Generate blocks.s from .fth source files

Scans the blocks/ directory for files matching `block-NN.fth`, where NN
is a zero-padded decimal block number (e.g. block-00.fth, block-01.fth).

Each file must conform to the Forth screen layout:
  - At most 16 lines
  - Each line at most 64 characters (after stripping trailing whitespace/newline)
  - Fewer than 16 lines are padded with blank lines
  - Lines shorter than 64 characters are space-padded to 64

The script emits blocks.s with:
  - A `block_base` symbol pointing to the start of the block region
  - One 1024-byte block per file, in block-number order
  - Zero-filled blocks for any gaps in the numbering sequence

Usage:
    python3 tools/mkblocks.py [-o blocks.s] [blocks_dir]
"""

import argparse
import glob
import os
import re
import sys


BLOCK_SIZE = 1024
LINES_PER_BLOCK = 16
CHARS_PER_LINE = 64


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate blocks.s from .fth source files")
    parser.add_argument("-o", "--output", default="blocks.s",
                        help="Output assembly file (default: blocks.s)")
    parser.add_argument("directory", nargs="?", default="blocks",
                        help="Directory containing block-NN.fth files (default: blocks)")
    return parser.parse_args()


def find_blocks(directory: str) -> dict[int, str]:
    """Return {block_number: filepath} for all block-NN.fth files."""
    blocks: dict[int, str] = {}
    pattern = os.path.join(directory, "block-*.fth")
    for path in sorted(glob.glob(pattern)):
        basename = os.path.basename(path)
        m = re.match(r"^block-(\d+)\.fth$", basename)
        if not m:
            print(f"Warning: skipping file with unexpected name: {path}", file=sys.stderr)
            continue
        block_num = int(m.group(1))
        if block_num in blocks:
            print(f"Error: duplicate block number {block_num}: {path} and {blocks[block_num]}",
                  file=sys.stderr)
            sys.exit(1)
        blocks[block_num] = path
    return blocks


def read_block(path: str) -> list[str]:
    """Read a .fth file and return exactly 16 lines of exactly 64 chars.

    Raises ValueError if a line exceeds 64 chars or the file exceeds 16 lines.
    """
    with open(path, "r", encoding="utf-8") as f:
        raw_lines = f.readlines()

    lines: list[str] = []
    for lineno, raw in enumerate(raw_lines, start=1):
        stripped = raw.rstrip("\r\n").rstrip()
        if len(stripped) > CHARS_PER_LINE:
            raise ValueError(
                f"{path}:{lineno}: line is {len(stripped)} characters, "
                f"max is {CHARS_PER_LINE}"
            )
        lines.append(stripped.ljust(CHARS_PER_LINE))

    if len(lines) > LINES_PER_BLOCK:
        raise ValueError(
            f"{path}: file has {len(lines)} lines, max is {LINES_PER_BLOCK}"
        )

    while len(lines) < LINES_PER_BLOCK:
        lines.append(" " * CHARS_PER_LINE)

    return lines


def build_blocks(blocks: dict[int, str]) -> tuple[list[bytes], list[str]]:
    """Return block data and error messages for all blocks.

    If no blocks are found, returns a single zero-filled block so the
    kernel can still build.
    """
    if not blocks:
        return [b"\x00" * BLOCK_SIZE], []

    max_block = max(blocks.keys())

    data: list[bytes] = []
    errors: list[str] = []
    has_errors = False

    for i in range(max_block + 1):
        if i in blocks:
            try:
                lines = read_block(blocks[i])
                block_bytes = "".join(lines).encode("ascii")
                assert len(block_bytes) == BLOCK_SIZE
                data.append(block_bytes)
            except ValueError as e:
                if isinstance(e, UnicodeEncodeError):
                    error_msg = f"Error: {blocks[i]}: non-ASCII character detected"
                else:
                    error_msg = f"Error: {e}"
                errors.append(error_msg)
                has_errors = True
                data.append(b"\x00" * BLOCK_SIZE)
        else:
            data.append(b"\x00" * BLOCK_SIZE)

    if has_errors:
        return data, errors

    return data, []


def emit_assembly(blocks: list[bytes], output_path: str) -> None:
    """Write blocks.s with the given block data."""
    with open(output_path, "w") as f:
        f.write("/* blocks.s - Generated by tools/mkblocks.py */\n")
        f.write("/* DO NOT EDIT */\n\n")
        f.write('    .section .rodata\n')
        f.write('    .balign 4\n')
        f.write('    .globl  block_base\n')
        f.write("block_base:\n")

        for i, block in enumerate(blocks):
            f.write(f"/* block {i} */\n")
            parts = [f"0x{b:02x}" for b in block]
            for j in range(0, len(parts), 16):
                chunk = ", ".join(parts[j:j + 16])
                f.write(f"    .byte {chunk}\n")


def main() -> None:
    args = parse_args()

    if not os.path.isdir(args.directory):
        print(f"Error: directory not found: {args.directory}", file=sys.stderr)
        sys.exit(1)

    blocks = find_blocks(args.directory)
    data, errors = build_blocks(blocks)

    if errors:
        for err in errors:
            print(err, file=sys.stderr)
        print(f"Error: {len(errors)} error(s) found, not generating {args.output}",
              file=sys.stderr)
        sys.exit(1)

    emit_assembly(data, args.output)
    print(f"Generated {args.output}: {len(data)} block(s), "
          f"{len(data) * BLOCK_SIZE} bytes", file=sys.stderr)


if __name__ == "__main__":
    main()
